name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ubuntu
        KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$KEY" > private_key.pem
        chmod 600 private_key.pem
        rsync -avz -e "ssh -i private_key.pem" --delete ./index.php $EC2_USER@$EC2_HOST:/var/www/html/
